### ISSUE TITLE
Ping Timeout, round 2

### ISSUE THREAD

**Issue by GastonGit** [GastonGit/Lurk.Server#10]
This has started to happen quite often since at least 3.2.2.

`2|htc-serv | 2022-01-04 08:47 +00:00: [08:47] error: Ping timeout.`

```
2|htc-serv | 2022-01-04 08:48 +00:00: TMI.JS :: DISCONNECTED ::
2|htc-serv | 2022-01-04 08:48 +00:00: /Hot-Twitch-Clips/server/dist/lib/TwitchChatInterface.js:31
2|htc-serv | 2022-01-04 08:48 +00:00:             throw Error('UNABLE TO CONNECT');
2|htc-serv | 2022-01-04 08:48 +00:00:                   ^
2|htc-serv | 2022-01-04 08:48 +00:00: Error: UNABLE TO CONNECT
2|htc-serv | 2022-01-04 08:48 +00:00:     at client.<anonymous> (Hot-Twitch-Clips/server/dist/lib/TwitchChatInterface.js:31:19)
2|htc-serv | 2022-01-04 08:48 +00:00:     at client.EventEmitter.emit (Hot-Twitch-Clips/server/node_modules/tmi.js/lib/events.js:79:13)
2|htc-serv | 2022-01-04 08:48 +00:00:     at client.emits (Hot-Twitch-Clips/server/node_modules/tmi.js/lib/client.js:79:13)
2|htc-serv | 2022-01-04 08:48 +00:00:     at client._onClose (Hot-Twitch-Clips/server/node_modules/tmi.js/lib/client.js:1240:8)
2|htc-serv | 2022-01-04 08:48 +00:00:     at WebSocket.onClose (Hot-Twitch-Clips/server/node_modules/ws/lib/event-target.js:136:16)
2|htc-serv | 2022-01-04 08:48 +00:00:     at WebSocket.emit (node:events:365:28)
2|htc-serv | 2022-01-04 08:48 +00:00:     at WebSocket.emit (node:domain:470:12)
2|htc-serv | 2022-01-04 08:48 +00:00:     at WebSocket.emitClose (Hot-Twitch-Clips/server/node_modules/ws/lib/websocket.js:198:10)
2|htc-serv | 2022-01-04 08:48 +00:00:     at Receiver.receiverOnFinish (Hot-Twitch Clips/server/node_modules/ws/lib/websocket.js:815:20)
2|htc-serv | 2022-01-04 08:48 +00:00:     at Receiver.emit (node:events:365:28)
```

**Comment by GastonGit** [comment]
Possibly related: https://discuss.dev.twitch.tv/t/twitch-keeps-giving-me-the-error-no-response-from-twitch/21341/5

**Comment by GastonGit** [comment]
Solved by: https://github.com/GastonGit/Lurk.Server/commit/efbff9d06823bcc7d36e5081e7a5fb868856acf5
